### ISSUE TITLE
(1.19.4) - Backpack doesn't function.

### ISSUE THREAD

**Issue by Tursiops-G** [AmibeSkyfy16/SingleBackpack#3]
Can't open it - Right-click does nothing.

No crash, but Log spammed with:

[13:21:22] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2886@38397ed7, suppressing error
java.lang.NullPointerException: Cannot read field "clientRespond" because the return value of "java.util.Map.get(Object)" is null
at ch.skyfy.enderbackpack.BackpackItem.method_7836(BackpackItem.java:35) ~[enderbackpack-1.5.2_1.19.4.jar:?]
at net.minecraft.class_1799.method_7913(class_1799.java:286) ~[client-intermediary.jar:?]
at net.minecraft.class_3225.method_14256(class_3225.java:290) ~[client-intermediary.jar:?]
at net.minecraft.class_3244.method_12065(class_3244.java:1177) ~[client-intermediary.jar:?]
at net.minecraft.class_2886.method_12550(class_2886.java:29) ~[client-intermediary.jar:?]
at net.minecraft.class_2886.method_11054(class_2886.java:7) ~[client-intermediary.jar:?]
at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:786) ~[client-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[client-intermediary.jar:?]
at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:768) ~[client-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:762) ~[client-intermediary.jar:?]
at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:747) ~[client-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:679) ~[client-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266) ~[client-intermediary.jar:?]
at java.lang.Thread.run(Unknown Source) ~[?:?]
 --->repeat

**Comment by Tursiops-G** [comment]
Fixed in release 1.5.3
